input {
  beats {
    port => 5044
  }
}

filter {
  if [message] =~ /\[ERROR\]/ {
    mutate {
      add_field => { "log_level" => "ERROR" }
    }
  } else if [message] =~ /\[WARNING\]/ {
    mutate {
      add_field => { "log_level" => "WARNING" }
    }
  } else if [message] =~ /\[INFO\]/ {
    mutate {
      add_field => { "log_level" => "INFO" }
    }
  } else {
    mutate {
      add_field => { "log_level" => "DEBUG" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "app-logs-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}